import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { clampArtifactFrameHeight } from '@/features/artifact-preview/sandboxHtml'

const card = readFileSync('src/components/artifacts/ArtifactPreviewCard.vue', 'utf8')
const sandbox = readFileSync('src/features/artifact-preview/sandboxHtml.ts', 'utf8')
const scrollCoordinator = readFileSync('src/lib/scrollGestureCoordinator.ts', 'utf8')
const backend = readFileSync('src-tauri/src/artifact_preview.rs', 'utf8')
const blockText = readFileSync('src/components/blocks/BlockText.vue', 'utf8')

describe('artifact previews and local file links', () => {
  it('keeps scripts inert until the user enables them inside an opaque iframe', () => {
    expect(card).toContain('sandbox="allow-scripts"')
    expect(card).not.toContain('allow-same-origin')
    expect(sandbox).toContain("querySelectorAll('script')")
    expect(sandbox).toContain("startsWith('on')")
    expect(sandbox).toContain("`script-src 'nonce-${options.scriptNonce}'`")
    expect(sandbox).toContain('"script-src-attr \'none\'"')
    expect(sandbox).toContain("setAttribute('nonce', options.scriptNonce)")
    expect(sandbox).toContain('neutralizeArtifactScripts(document, options.allowArtifactScripts)')
    expect(sandbox).toContain('template[')
    expect(sandbox).toContain("source.hasAttribute('src')")
    expect(sandbox).toContain('window.__TAURI_INTERNALS__ || window.isTauri')
    expect(sandbox).toContain('ARTIFACT_RUNTIME_BLOCKED_MESSAGE')
    expect(card).toContain("$t('artifactPreview.allowScripts')")
    expect(card).toContain(':aria-pressed="artifactScriptsAllowed"')
    expect(sandbox).toContain('new ResizeObserver(schedule)')
    expect(sandbox).toContain('document.createRange()')
    expect(sandbox).toContain('setTimeout(() => requestAnimationFrame(measure), 100)')
    expect(sandbox).toContain("parent.postMessage({ type, token, height, fillsViewport }, '*')")
    expect(sandbox).toContain("ARTIFACT_WHEEL_BOUNDARY_MESSAGE")
    expect(sandbox).toContain("addEventListener('wheel'")
    expect(sandbox).toContain("event.preventDefault()")
    expect(card).toContain('class="artifact-scroll-shield"')
    expect(scrollCoordinator).toContain("data-monet-scroll-shield-active")
    expect(scrollCoordinator).toContain("GESTURE_IDLE_MS = 160")
    expect(sandbox).toContain('"connect-src \'none\'"')
    expect(card).toContain('referrerpolicy="no-referrer"')
    expect(card).toContain('event.source !== frame.contentWindow')
    expect(card).toContain('data.token !== sandboxMessageToken.value')
    expect(sandbox).toContain("querySelectorAll('meta[http-equiv]')")
    expect(sandbox).toContain("querySelectorAll('a, area')")
    expect(sandbox).toContain("querySelectorAll('base')")
    expect(sandbox).toContain('html { overflow-y: auto !important; }')
    expect(sandbox).toContain('body { overflow-y: visible !important; }')
  })

  it('caps HTML at a portrait 3:4 frame and disposes offscreen payloads', () => {
    expect(sandbox).toContain('frameWidth) * 4 / 3')
    expect(card).toContain("rootMargin: '200px 0px'")
    expect(card).toContain('}, 500)')
    expect(card).toContain('artifact.value = null')
    expect(clampArtifactFrameHeight(900, 600)).toBe(800)
    expect(clampArtifactFrameHeight(100, 600)).toBe(240)
    expect(clampArtifactFrameHeight(900, 500)).toBe(666)
    expect(clampArtifactFrameHeight(Number.POSITIVE_INFINITY, 600)).toBe(800)
    expect(card).toContain('Number.POSITIVE_INFINITY')
    expect(card).toContain('contentFillsViewport')
  })

  it('opens image artifacts in an accessible lightbox', () => {
    expect(card).toContain('class="artifact-image-open"')
    expect(card).toContain('@click="openImageLightbox"')
    expect(card).toContain('class="artifact-image-lightbox"')
    expect(card).toContain('aria-modal="true"')
    expect(card).toContain("event.key === 'Escape'")
    expect(card).toContain('@click.self="closeImageLightbox()"')
    expect(card).toContain('@wheel.prevent.stop')
  })

  it('allows artifact previews outside the workspace after canonicalization', () => {
    expect(backend).toContain('let root = root')
    expect(backend).toContain('.canonicalize()')
    expect(backend).toContain('return resolve_local_file(root, requested)')
    expect(backend).toContain('let resolved = resolve_local_file_with_fallback(')
    expect(backend).not.toContain('candidate.starts_with(&canonical_root)')
  })

  it('opens Markdown file links outside the workspace after canonicalization', () => {
    expect(blockText).toContain("await invoke('open_local_file', {")
    expect(blockText).toContain('fallbackRoot: sessionFileFallbackRoot?.value ?? null')
    expect(backend).toContain('pub fn open_local_file(')
    expect(backend).toContain('fallback_root: Option<String>')
    expect(backend).toContain('if !candidate.is_file()')
  })
})
