import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

function source(path: string): string {
  return readFileSync(fileURLToPath(new URL(path, import.meta.url)), 'utf8')
}

describe('工具调用分层折叠', () => {
  it('常规动作保持分组,编排调用压成标题轨道,图片在右侧纸片展开', () => {
    const group = source('../../src/components/ToolProcessGroup.vue')
    const list = source('../../src/components/ContentBlockList.vue')
    const items = source('../../src/components/ToolProcessItems.vue')
    const item = source('../../src/components/ToolProcessItem.vue')
    const resultImages = source('../../src/components/ToolResultImages.vue')
    const processTrack = source('../../src/components/ToolProcessTrack.vue')
    const imageStack = source('../../src/components/ToolImageStack.vue')
    const nativeTurn = source('../../src/components/MessageGroup.vue')
    const standardTurn = source('../../src/components/engine/EngineConversationGroup.vue')
    const resultCard = source('../../src/components/ToolResultPreviewCard.vue')
    const inlineImage = source('../../src/components/blocks/BlockImage.vue')
    const assetImage = source('../../src/components/engine/EngineAssetImage.vue')

    expect(group).toContain('nested')
    expect(items).toContain('nested?: boolean')
    expect(items).toContain(':foldable="!props.nested"')
    expect(item).toContain('foldable?: boolean')
    expect(item).toContain('v-if="!orchestration && (!foldable || expanded)"')
    expect(list).toContain('v-else-if="isOrchestrationToolSegment(segment.tools)"')
    expect(item).toContain('v-if="foldable && canExpand"')
    expect(item).toContain('toolDisplayTitle(props.tool)')
    expect(item).toContain('const resultExpanded = ref(false)')
    expect(item).toContain('v-if="orchestration && result && (!foldable || expanded)"')
    expect(item).toContain('<ToolResultPreviewCard')
    expect(item).toContain(':expanded="resultExpanded"')
    expect(item).toContain('@toggle="toggleResult"')
    expect(item).toContain('if (!value) resultExpanded.value = false')
    expect(item).toContain('<ToolResultImages')
    expect(item).toContain('v-if="showImages && imageCount > 0"')
    expect(item.indexOf('<ToolResultImages')).toBeLessThan(
      item.indexOf('v-if="!orchestration && (!foldable || expanded)"'),
    )
    expect(resultImages).toContain('flex-wrap: wrap')
    expect(resultImages).toContain('flex: 0 1 240px')
    expect(resultImages).toContain('width: 240px')
    expect(resultImages).toContain('height: 160px')
    expect(resultImages).toContain('<BlockImage')
    expect(resultImages).toContain('<EngineAssetImage')
    expect(inlineImage).toContain('@click="expanded = true"')
    expect(assetImage).toContain('@click="openLightbox"')
    expect(group).toContain('latestOnly?: boolean')
    expect(group).toContain('titlesOnly?: boolean')
    expect(group).toContain('latestChronologicalItem(props.tools)')
    expect(group).toContain('toolDisplayTitle(latestTool)')
    expect(group).toContain('class="tool-title-history-row"')
    expect(group).toContain(':show-images="showImages"')
    expect(processTrack).toContain('regularTools')
    expect(processTrack).toContain('orchestrationTools')
    expect(processTrack).toContain('latest-only')
    expect(processTrack).toContain('titles-only')
    expect(processTrack).toContain(':show-images="false"')
    expect(processTrack).toContain('<ToolImageStack')
    expect(processTrack).not.toContain('border: 1px')
    expect(imageStack).toContain('class="tool-image-stack-card"')
    expect(imageStack).toContain("const expanded = ref(false)")
    expect(imageStack).toContain('entries.value.map((entry, chronologicalIndex)')
    expect(imageStack).toContain('expanded.value ? allEntries : allEntries.slice(-1)')
    expect(imageStack).toContain("'z-index': String(chronologicalIndex + 1)")
    expect(imageStack).toContain('chronologicalIndex % EXPANDED_POSES.length')
    expect(imageStack).toContain('rail.value.scrollLeft = rail.value.scrollWidth')
    expect(imageStack).toContain('class="tool-image-stack-expand"')
    expect(imageStack).toContain('@click.stop="expanded = true"')
    expect(imageStack).toContain('v-if="!expanded && entries.length > 1"')
    expect(imageStack).toContain("'has-multiple': entries.length > 1")
    expect(imageStack).toContain("'has-many': entries.length > 2")
    expect(imageStack).not.toContain('class="tool-image-stack-open"')
    expect(imageStack).not.toContain('pointer-events: none; }')
    expect(imageStack).toContain('position: absolute')
    expect(imageStack).toContain('.tool-image-stack.is-expanded .tool-image-stack-card')
    expect(imageStack).toContain('<BlockImage')
    expect(imageStack).toContain('<EngineAssetImage')
    expect(imageStack).toContain('@container (max-width: 420px)')
    expect(imageStack).toContain('overflow-x: auto')
    expect(imageStack).toContain('flex: 0 0 150px')
    expect(imageStack).toContain('margin-inline-start: auto')
    expect(imageStack).toContain('object-fit: contain')
    expect(imageStack).toContain('padding: 10px 12px 18px')
    expect(imageStack).toContain('scrollbar-width: none')
    expect(imageStack).toContain('::-webkit-scrollbar')
    expect(inlineImage).toContain('tabindex="0"')
    expect(inlineImage).toContain('@keydown.enter.prevent="expanded = true"')
    expect(nativeTurn).toContain('<ToolProcessTrack')
    expect(standardTurn).toContain('<ToolProcessTrack')
    expect(resultCard).toContain('tool-result-clamp-3')
    expect(resultCard).not.toContain('tool-result-preview-images')
    expect(resultCard).not.toContain('tool-result-clamp-2')
    expect(resultCard).toContain("@click=\"emit('toggle', $event)\"")
    expect(item).toContain(':aria-expanded="expanded"')
    expect(item).toContain(':aria-controls="resultContentId"')
    expect(item).toContain('tool-fold-line:focus-visible')
    expect(item).toContain("font-size: 11px")
    expect(item).toContain("font-weight: 450")
  })
})

describe('已思考标签', () => {
  it('所有内置语言都不展示加密说明括号', () => {
    const localeDir = fileURLToPath(new URL('../../src/locales/', import.meta.url))
    for (const name of readdirSync(localeDir).filter(name => name.endsWith('.json'))) {
      const locale = JSON.parse(readFileSync(`${localeDir}/${name}`, 'utf8')) as {
        block?: { thinkingRedacted?: string }
      }
      expect(locale.block?.thinkingRedacted, name).not.toMatch(/[()（）]/)
    }
  })
})
